config/routes.rb
Rails.application.routes.draw do
  resources :seen_animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/seen_animal.rb
class SeenAnimal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/seen_animals_controller.rb
class SeenAnimalsController < ApplicationController
  before_action :set_seen_animal, only: [:show, :edit, :update, :destroy]

  # GET /seen_animals
  # GET /seen_animals.json
  def index
    @seen_animals = SeenAnimal.all
  end

  # GET /seen_animals/1
  # GET /seen_animals/1.json
  def show
  end

  # GET /seen_animals/new
  def new
    @seen_animal = SeenAnimal.new
  end

  # GET /seen_animals/1/edit
  def edit
  end

  # POST /seen_animals
  # POST /seen_animals.json
  def create
    @seen_animal = SeenAnimal.new(seen_animal_params)

    respond_to do |format|
      if @seen_animal.save
        format.html { redirect_to @seen_animal, notice: 'Seen animal was successfully created.' }
        format.json { render :show, status: :created, location: @seen_animal }
      else
        format.html { render :new }
        format.json { render json: @seen_animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seen_animals/1
  # PATCH/PUT /seen_animals/1.json
  def update
    respond_to do |format|
      if @seen_animal.update(seen_animal_params)
        format.html { redirect_to @seen_animal, notice: 'Seen animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @seen_animal }
      else
        format.html { render :edit }
        format.json { render json: @seen_animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seen_animals/1
  # DELETE /seen_animals/1.json
  def destroy
    @seen_animal.destroy
    respond_to do |format|
      format.html { redirect_to seen_animals_url, notice: 'Seen animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seen_animal
      @seen_animal = SeenAnimal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seen_animal_params
      params.require(:seen_animal).permit(:id, :species, :count_of_times_seen, :location_of_last_seen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seen_animals_helper.rb
module SeenAnimalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SafariVacation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seen_animals/_form.html.erb
<%= form_with(model: seen_animal, local: true) do |form| %>
  <% if seen_animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seen_animal.errors.count, "error") %> prohibited this seen_animal from being saved:</h2>

      <ul>
      <% seen_animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :species %>
    <%= form.text_field :species %>
  </div>

  <div class="field">
    <%= form.label :count_of_times_seen %>
    <%= form.number_field :count_of_times_seen %>
  </div>

  <div class="field">
    <%= form.label :location_of_last_seen %>
    <%= form.text_field :location_of_last_seen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seen_animals/edit.html.erb
<h1>Editing Seen Animal</h1>

<%= render 'form', seen_animal: @seen_animal %>

<%= link_to 'Show', @seen_animal %> |
<%= link_to 'Back', seen_animals_path %>

app/views/seen_animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seen Animals</h1>

<table>
  <thead>
    <tr>
      <th>Species</th>
      <th>Count of times seen</th>
      <th>Location of last seen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seen_animals.each do |seen_animal| %>
      <tr>
        <td><%= seen_animal.species %></td>
        <td><%= seen_animal.count_of_times_seen %></td>
        <td><%= seen_animal.location_of_last_seen %></td>
        <td><%= link_to 'Show', seen_animal %></td>
        <td><%= link_to 'Edit', edit_seen_animal_path(seen_animal) %></td>
        <td><%= link_to 'Destroy', seen_animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seen Animal', new_seen_animal_path %>

app/views/seen_animals/new.html.erb
<h1>New Seen Animal</h1>

<%= render 'form', seen_animal: @seen_animal %>

<%= link_to 'Back', seen_animals_path %>

app/views/seen_animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Species:</strong>
  <%= @seen_animal.species %>
</p>

<p>
  <strong>Count of times seen:</strong>
  <%= @seen_animal.count_of_times_seen %>
</p>

<p>
  <strong>Location of last seen:</strong>
  <%= @seen_animal.location_of_last_seen %>
</p>

<%= link_to 'Edit', edit_seen_animal_path(@seen_animal) %> |
<%= link_to 'Back', seen_animals_path %>